export const LOAD_USERS_ATTEMPT = 'LOAD_USERS_ATTEMPT';
export const LOAD_USERS_SUCCESS = 'LOAD_USERS_SUCCESS';
export const LOAD_USERS_ERROR = 'LOAD_USERS_ERROR';

export const CREATE_USER_ATTEMPT = 'CREATE_USER_ATTEMPT';
export const CREATE_USER_SUCCESS = 'CREATE_USER_SUCCESS';
export const CREATE_USER_ERROR = 'CREATE_USER_ERROR';

export const SAVE_ROLE = 'SAVE_ROLE';

export const SAVE_ACCESS_TOKEN = 'SAVE_ACCESS_TOKEN';
export const CHANGE_LANGUAGE = 'CHANGE_LANGUAGE';

export const LOGOUT = 'LOGOUT';

export const LOGIN_ATTEMPT = 'LOGIN_ATTEMPT';
export const LOGIN_SUCCESS = 'LOGIN_SUCCESS';
export const LOGIN_ERROR = 'LOGIN_ERROR';

export const REGISTER_USER_ATTEMPT = 'REGISTER_USER_ATTEMPT';
export const REGISTER_USER_SUCCES = 'REGISTER_USER_SUCCES';
export const REGISTER_USER_ERROR = 'REGISTER_USER_ERROR';

export const CHANGE_THEME = 'CHANGE_THEME';

export const LOAD_ROLES_ATTEMPT = 'LOAD_ROLES_ATTEMPT';
export const LOAD_ROLES_SUCCESS = 'LOAD_ROLES_SUCCESS';
export const LOAD_ROLES_ERROR = 'LOAD_ROLES_ERROR';